tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "git"
brew "postgresql", restart_service: true
brew "rbenv"
brew "tree"
brew "zsh"
brew "zsh-completions"
brew "mongodb/brew/mongodb-community"
cask "insomnia"
cask "iterm2"
cask "visual-studio-code"
